# Generated by Django 4.2.19 on 2025-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('adddress', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('activate', models.BooleanField()),
            ],
        ),
    ]
